### ISSUE TITLE
How is Referencedata.json generated?

### ISSUE THREAD

**Issue by AnushreeParmar13** [kvaes/azure-vmchooser-database#3]
From the APIs, I can get the rate card for VMs. However, I am looking for logic used to populate referencedata.json. Is this is a static file, or generated using response from API? And if generated through API, could you please point me to the code snippets/file from github solution?
Thanks in advance

**Comment by kvaes** [comment]
@AnushreeParmar13 ; referencedata.json is manual labor... yes, I know... really fun task! #sarcasm
There is no API that exposes (the majority of) that data.

(my apologies for the late reply, it seems I didn't have my notifications enabled for this repo)
