### ISSUE TITLE
How do you get the sqlpricing.json

### ISSUE THREAD

**Issue by sujithq** [kvaes/azure-vmchooser-database#4]
In https://github.com/kvaes/azure-vmchooser-database/blob/master/sql/parse.js you refer to sqlpricing.json. 
In https://github.com/kvaes/azure-vmchooser-database/blob/master/compute/parse-sql.js you refer to apipricing-software.json, apipricing-software-ri1y.json and apipricing-software-ri3y.json.

How do you generate these files?

**Comment by kvaes** [comment]
Replied on Twitter ; https://twitter.com/SujithQ/status/1184008376554049537

The only supported way (which was one of the reasons VMchooser was initially shut down) is working via the RateCard APIs. The APIs I used were not officially supported, hence why I haven't documented the origin of them.

Linked issue ; https://github.com/kvaes/azure-vmchooser-frontend-v3/issues/15
